puts "The students of my cohort at Makers Academy"
puts "-------------"
puts "Christopher Ward"
puts "Rizwan Ali"
puts "Vanessa Virgitti"
puts "Tommaso Bratto"
puts "Joe Newman"
puts "Loris Fochesato"
puts "Guido Vita Finzi"
puts "Tom Coakes"
puts "Kevin Lanzon"
puts "Sebastien Pires"
puts "Yannick Brunner"
puts "Costas Sarris"
puts "Diego Romero"
puts "Erik Griffin"
puts "Thomas Strothjohann"
puts "Alex Parkinson"
puts "Carrie Christenson"
puts "Julian Veling"
puts "Edward Brown"
puts "Meads Chalcroft"
puts "Sean Haughton"
puts "Paul Fitzgerald"
puts "Munded"
puts "Phil Brockwell"
puts "Gabe"
puts "Kate Beavis"
puts "Louise"
print "Overall, we have "
print 27
puts " great students"